// Code generated by Golem. DO NOT EDIT.
// Source: https://github.com/t-geindre/golem

package component

import "github.com/t-geindre/golem/pkg/golem"

type ColorGolemI interface {
	GetColor() *Color
}

func (p *Color) GetColor() *Color {
	return p
}

func GetColor(e golem.Entity) *Color {
	if p, ok := e.(ColorGolemI); ok {
		return p.GetColor()
	}
	return nil
}