// Code generated by Golem. DO NOT EDIT.
// Source: https://github.com/t-geindre/golem

package component

import "github.com/t-geindre/golem/pkg/golem"

type GeometryGolemI interface {
	GetGeometry() *Geometry
}

func (p *Geometry) GetGeometry() *Geometry {
	return p
}

func GetGeometry(e golem.Entity) *Geometry {
	if p, ok := e.(GeometryGolemI); ok {
		return p.GetGeometry()
	}
	return nil
}