// Code generated by Golem. DO NOT EDIT.
// Source: https://github.com/t-geindre/golem

package mock

import "github.com/t-geindre/golem/pkg/golem"

type CompAGolemI interface {
	GetCompA() *CompA
}

func (p *CompA) GetCompA() *CompA {
	return p
}

func GetCompA(e golem.Entity) *CompA {
	if p, ok := e.(CompAGolemI); ok {
		return p.GetCompA()
	}
	return nil
}