// Code generated by Golem. DO NOT EDIT.
// Source: https://github.com/t-geindre/golem

package mock

import "github.com/t-geindre/golem/pkg/golem"

type CompCGolemI interface {
	GetCompC() *CompC
}

func (p *CompC) GetCompC() *CompC {
	return p
}

func GetCompC(e golem.Entity) *CompC {
	if p, ok := e.(CompCGolemI); ok {
		return p.GetCompC()
	}
	return nil
}