// Code generated by Golem. DO NOT EDIT.
// Source: https://github.com/t-geindre/golem

package mock

import "github.com/t-geindre/golem/pkg/golem"

type CompBGolemI interface {
	GetCompB() *CompB
}

func (p *CompB) GetCompB() *CompB {
	return p
}

func GetCompB(e golem.Entity) *CompB {
	if p, ok := e.(CompBGolemI); ok {
		return p.GetCompB()
	}
	return nil
}