// Code generated by Golem. DO NOT EDIT.
// Source: https://github.com/t-geindre/golem

package component

import "github.com/t-geindre/golem/pkg/golem"

type AnimationSetGolemI interface {
	GetAnimationSet() *AnimationSet
}

func (p *AnimationSet) GetAnimationSet() *AnimationSet {
	return p
}

func GetAnimationSet(e golem.Entity) *AnimationSet {
	if p, ok := e.(AnimationSetGolemI); ok {
		return p.GetAnimationSet()
	}
	return nil
}