// Code generated by Golem. DO NOT EDIT.
// Source: https://github.com/t-geindre/golem

package component

import "github.com/t-geindre/golem/pkg/golem"

type ControlsGolemI interface {
	GetControls() *Controls
}

func (p *Controls) GetControls() *Controls {
	return p
}

func GetControls(e golem.Entity) *Controls {
	if p, ok := e.(ControlsGolemI); ok {
		return p.GetControls()
	}
	return nil
}