// Code generated by Golem. DO NOT EDIT.
// Source: https://github.com/t-geindre/golem

package component

import "github.com/t-geindre/golem/pkg/golem"

type DespawnGolemI interface {
	GetDespawn() *Despawn
}

func (p *Despawn) GetDespawn() *Despawn {
	return p
}

func GetDespawn(e golem.Entity) *Despawn {
	if p, ok := e.(DespawnGolemI); ok {
		return p.GetDespawn()
	}
	return nil
}