// Code generated by Golem. DO NOT EDIT.
// Source: https://github.com/t-geindre/golem

package component

import "github.com/t-geindre/golem/pkg/golem"

type LifeGolemI interface {
	GetLife() *Life
}

func (p *Life) GetLife() *Life {
	return p
}

func GetLife(e golem.Entity) *Life {
	if p, ok := e.(LifeGolemI); ok {
		return p.GetLife()
	}
	return nil
}