// Code generated by Golem. DO NOT EDIT.
// Source: https://github.com/t-geindre/golem

package component

import "github.com/t-geindre/golem/pkg/golem"

type LifetimeGolemI interface {
	GetLifetime() *Lifetime
}

func (p *Lifetime) GetLifetime() *Lifetime {
	return p
}

func GetLifetime(e golem.Entity) *Lifetime {
	if p, ok := e.(LifetimeGolemI); ok {
		return p.GetLifetime()
	}
	return nil
}