// Code generated by Golem. DO NOT EDIT.
// Source: https://github.com/t-geindre/golem

package component

import "github.com/t-geindre/golem/pkg/golem"

type PositionGolemI interface {
	GetPosition() *Position
}

func (p *Position) GetPosition() *Position {
	return p
}

func GetPosition(e golem.Entity) *Position {
	if p, ok := e.(PositionGolemI); ok {
		return p.GetPosition()
	}
	return nil
}