// Code generated by Golem. DO NOT EDIT.
// Source: https://github.com/t-geindre/golem

package component

import "github.com/t-geindre/golem/pkg/golem"

type ShootGolemI interface {
	GetShoot() *Shoot
}

func (p *Shoot) GetShoot() *Shoot {
	return p
}

func GetShoot(e golem.Entity) *Shoot {
	if p, ok := e.(ShootGolemI); ok {
		return p.GetShoot()
	}
	return nil
}