// Code generated by Golem. DO NOT EDIT.
// Source: https://github.com/t-geindre/golem

package component

import "github.com/t-geindre/golem/pkg/golem"

type BoundariesGolemI interface {
	GetBoundaries() *Boundaries
}

func (p *Boundaries) GetBoundaries() *Boundaries {
	return p
}

func GetBoundaries(e golem.Entity) *Boundaries {
	if p, ok := e.(BoundariesGolemI); ok {
		return p.GetBoundaries()
	}
	return nil
}