// Code generated by Golem. DO NOT EDIT.
// Source: https://github.com/t-geindre/golem

package component

import "github.com/t-geindre/golem/pkg/golem"

type LifecycleGolemI interface {
	GetLifecycle() *Lifecycle
}

func (p *Lifecycle) GetLifecycle() *Lifecycle {
	return p
}

func GetLifecycle(e golem.Entity) *Lifecycle {
	if p, ok := e.(LifecycleGolemI); ok {
		return p.GetLifecycle()
	}
	return nil
}