// Code generated by Golem. DO NOT EDIT.
// Source: https://github.com/t-geindre/golem

package component

import "github.com/t-geindre/golem/pkg/golem"

type OpacityGolemI interface {
	GetOpacity() *Opacity
}

func (p *Opacity) GetOpacity() *Opacity {
	return p
}

func GetOpacity(e golem.Entity) *Opacity {
	if p, ok := e.(OpacityGolemI); ok {
		return p.GetOpacity()
	}
	return nil
}