// Code generated by Golem. DO NOT EDIT.
// Source: https://github.com/t-geindre/golem

package component

import "github.com/t-geindre/golem/pkg/golem"

type RotationGolemI interface {
	GetRotation() *Rotation
}

func (p *Rotation) GetRotation() *Rotation {
	return p
}

func GetRotation(e golem.Entity) *Rotation {
	if p, ok := e.(RotationGolemI); ok {
		return p.GetRotation()
	}
	return nil
}