// Code generated by Golem. DO NOT EDIT.
// Source: https://github.com/t-geindre/golem

package component

import "github.com/t-geindre/golem/pkg/golem"

type ScaleGolemI interface {
	GetScale() *Scale
}

func (p *Scale) GetScale() *Scale {
	return p
}

func GetScale(e golem.Entity) *Scale {
	if p, ok := e.(ScaleGolemI); ok {
		return p.GetScale()
	}
	return nil
}