// Code generated by Golem. DO NOT EDIT.
// Source: https://github.com/t-geindre/golem

package component

import "github.com/t-geindre/golem/pkg/golem"

type ScreenScaleGolemI interface {
	GetScreenScale() *ScreenScale
}

func (p *ScreenScale) GetScreenScale() *ScreenScale {
	return p
}

func GetScreenScale(e golem.Entity) *ScreenScale {
	if p, ok := e.(ScreenScaleGolemI); ok {
		return p.GetScreenScale()
	}
	return nil
}