// Code generated by Golem. DO NOT EDIT.
// Source: https://github.com/t-geindre/golem

package component

import "github.com/t-geindre/golem/pkg/golem"

type SpriteGolemI interface {
	GetSprite() *Sprite
}

func (p *Sprite) GetSprite() *Sprite {
	return p
}

func GetSprite(e golem.Entity) *Sprite {
	if p, ok := e.(SpriteGolemI); ok {
		return p.GetSprite()
	}
	return nil
}