// Code generated by Golem. DO NOT EDIT.
// Source: https://github.com/t-geindre/golem

package component

import "github.com/t-geindre/golem/pkg/golem"

type TextGolemI interface {
	GetText() *Text
}

func (p *Text) GetText() *Text {
	return p
}

func GetText(e golem.Entity) *Text {
	if p, ok := e.(TextGolemI); ok {
		return p.GetText()
	}
	return nil
}