// Code generated by Golem. DO NOT EDIT.
// Source: https://github.com/t-geindre/golem

package component

import "github.com/t-geindre/golem/pkg/golem"

type TransitionGolemI interface {
	GetTransition() *Transition
}

func (p *Transition) GetTransition() *Transition {
	return p
}

func GetTransition(e golem.Entity) *Transition {
	if p, ok := e.(TransitionGolemI); ok {
		return p.GetTransition()
	}
	return nil
}