// Code generated by Golem. DO NOT EDIT.
// Source: https://github.com/t-geindre/golem

package component

import "github.com/t-geindre/golem/pkg/golem"

type CameraGolemI interface {
	GetCamera() *Camera
}

func (p *Camera) GetCamera() *Camera {
	return p
}

func GetCamera(e golem.Entity) *Camera {
	if p, ok := e.(CameraGolemI); ok {
		return p.GetCamera()
	}
	return nil
}