name: 🚀 Update examples
on:
  push:
    branches:
      - master
    paths:
      - 'pkg/**'
      - 'go.mod'
      - 'go.sum'

jobs:
  update-examples:
    runs-on: ubuntu-latest
    env:
      DISPLAY: ':99.0'
    defaults:
      run:
        shell: bash
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y libasound2-dev libgl1-mesa-dev libxcursor-dev libxi-dev libxinerama-dev libxrandr-dev libxxf86vm-dev

      - name: Xvfb
        run: |
          Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Update golem
        run: |
          cd examples/camera
          go get github.com/t-geindre/golem@master
          cd ../nodes
          go get github.com/t-geindre/golem@master
          cd ../scenes
          go get github.com/t-geindre/golem@master
          cd ../shmup
          go get github.com/t-geindre/golem@master
          cd ../squares
          go get github.com/t-geindre/golem@master

      - name: Commit example update
        uses: EndBug/add-and-commit@v9
        with:
          add: 'examples/'
          message: 'Update examples dependencies'